import { Platform, StyleSheet } from "react-native";


export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f5f5f5' },
    header: {
        backgroundColor: '#1c348e',
        padding: 15,
        paddingTop: Platform.OS === 'android' ? 50 : 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e5c228',
    },
    btnVoltar: {
        position: 'absolute',
        left: 15,
        top: Platform.OS === 'android' ? 50 : 20,
        zIndex: 1,
    },
    headerTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
    calendarButton: {
        position: 'absolute',
        right: 15,
        top: Platform.OS === 'android' ? 40 : 20,
        zIndex: 1,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
    },
    emptyListContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyListText: { fontSize: 18, color: '#666', marginBottom: 10 },
    reloadButton: {
        backgroundColor: '#e5c228',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
        marginTop: 10,
    },
    reloadButtonText: { color: '#1c348e', fontWeight: 'bold' },
    listContent: { padding: 15 },
    alunoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 15,
        marginBottom: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 3,
    },
    alunoNome: { fontSize: 18, color: '#333', flex: 1 },
    iconContainer: { flexDirection: 'row', alignItems: 'center' },
    saveButton: {
        backgroundColor: '#1c348e',
        paddingVertical: 15,
        marginHorizontal: 15,
        marginTop: 10,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    saveButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
    saveButtonDisabled: { backgroundColor: '#a0a0a0' },
    previousListsButton: {
        backgroundColor: '#e5c228',
        paddingVertical: 15,
        marginHorizontal: 15,
        marginBottom: 30,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    previousListsButtonText: {
        color: '#1c348e',
        fontSize: 16,
        fontWeight: 'bold',
    },

    // --- Estilos para o Modal (DatePicker) ---
    modalBackground: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    datePickerContainer: {
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        width: '80%', // Ajuste conforme necessário
    },
    confirmButton: {
        marginTop: 20,
        backgroundColor: '#1c348e',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 5,
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },

    // --- Estilos para o Histórico de Datas (card de dia) ---
    diaCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 8,
        marginBottom: 10,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.41,
    },
    diaCardContent: {
        flex: 1,
        marginRight: 10,
    },
    diaCardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    diaCardSummary: {
        fontSize: 14,
        color: '#666',
    },
});